SITE_NAME = "Ridgeway Site"
SHIFT_NOTE = "Please check Block C before leadership asks."

SITE_ZONES = [
    {
        "id": "gate-1",
        "label": "Gate 1",
        "kind": "gate",
        "x": 8,
        "y": 84,
        "width": 14,
        "height": 12,
        "risk_weight": 2,
        "description": "Primary staff ingress used for standard shift changes.",
    },
    {
        "id": "gate-3",
        "label": "Gate 3",
        "kind": "gate",
        "x": 7,
        "y": 20,
        "width": 14,
        "height": 12,
        "risk_weight": 4,
        "description": "Service gate closest to the Block C perimeter road.",
    },
    {
        "id": "block-c",
        "label": "Block C",
        "kind": "storage",
        "x": 42,
        "y": 16,
        "width": 22,
        "height": 18,
        "risk_weight": 5,
        "description": "Restricted storage yard for high-value catalytic components.",
    },
    {
        "id": "checkpoint-alpha",
        "label": "Checkpoint Alpha",
        "kind": "checkpoint",
        "x": 28,
        "y": 44,
        "width": 16,
        "height": 12,
        "risk_weight": 3,
        "description": "Badge-controlled checkpoint for the northeast corridor.",
    },
    {
        "id": "yard-east",
        "label": "East Yard",
        "kind": "yard",
        "x": 67,
        "y": 46,
        "width": 19,
        "height": 20,
        "risk_weight": 3,
        "description": "Staging area for contractor vehicles and loading operations.",
    },
    {
        "id": "drone-bay",
        "label": "Drone Bay",
        "kind": "drone",
        "x": 77,
        "y": 11,
        "width": 13,
        "height": 11,
        "risk_weight": 2,
        "description": "Autonomous patrol launch and docking area.",
    },
]

OVERNIGHT_EVENTS = [
    {
        "id": "evt-001",
        "type": "fence-alert",
        "zone_id": "gate-3",
        "started_at": "2026-04-16T22:41:00Z",
        "ended_at": "2026-04-16T22:47:00Z",
        "title": "Fence vibration spike at Gate 3",
        "detail": "Perimeter sensor recorded repeated vibration bursts along the Gate 3 boundary line.",
        "severity": "medium",
        "confidence": 0.77,
        "actor": None,
        "metadata": {"source": "fence-line-sensor", "weather": "light wind"},
    },
    {
        "id": "evt-002",
        "type": "vehicle-track",
        "zone_id": "block-c",
        "started_at": "2026-04-16T22:54:00Z",
        "ended_at": "2026-04-16T23:09:00Z",
        "title": "Unplanned pickup loop near Block C",
        "detail": "A white utility pickup entered from the Gate 3 service road, paused near Block C, and exited without a matching work order.",
        "severity": "high",
        "confidence": 0.84,
        "actor": "Vehicle V-17",
        "metadata": {"plate_hint": "partial-781", "dwell_minutes": 9, "work_order_match": "none"},
    },
    {
        "id": "evt-003",
        "type": "badge-swipe",
        "zone_id": "checkpoint-alpha",
        "started_at": "2026-04-16T23:04:00Z",
        "ended_at": "2026-04-16T23:07:00Z",
        "title": "Three failed badge swipes",
        "detail": "Contractor Arun P. failed three badge attempts before access was denied.",
        "severity": "medium",
        "confidence": 0.91,
        "actor": "Arun P.",
        "metadata": {"attempts": 3, "outcome": "denied", "shift_roster_match": "expired contractor credential"},
    },
    {
        "id": "evt-004",
        "type": "camera-health",
        "zone_id": "block-c",
        "started_at": "2026-04-16T23:11:00Z",
        "ended_at": "2026-04-16T23:19:00Z",
        "title": "Camera packet loss near Block C",
        "detail": "Camera cam-n4 dropped frames for eight minutes during the suspicious vehicle dwell window.",
        "severity": "high",
        "confidence": 0.74,
        "actor": None,
        "metadata": {"packet_loss": "38%", "recorder": "cam-n4"},
    },
    {
        "id": "evt-005",
        "type": "drone-patrol",
        "zone_id": "block-c",
        "started_at": "2026-04-17T00:16:00Z",
        "ended_at": "2026-04-17T00:31:00Z",
        "title": "Autonomous patrol routed over Block C",
        "detail": "Drone R-12 rechecked Gate 3, Block C, and East Yard after the earlier perimeter anomaly.",
        "severity": "medium",
        "confidence": 0.95,
        "actor": "Drone R-12",
        "metadata": {"route": ["gate-3", "block-c", "yard-east"], "thermal_anomaly": "none", "object_detection": "fresh tire tracks"},
    },
    {
        "id": "evt-006",
        "type": "shift-note",
        "zone_id": "block-c",
        "started_at": "2026-04-17T05:41:00Z",
        "ended_at": None,
        "title": "Night supervisor note",
        "detail": SHIFT_NOTE,
        "severity": "high",
        "confidence": 0.99,
        "actor": "Raghav",
        "metadata": {"note_type": "handoff"},
    },
    {
        "id": "evt-007",
        "type": "vehicle-track",
        "zone_id": "yard-east",
        "started_at": "2026-04-16T21:50:00Z",
        "ended_at": "2026-04-16T22:08:00Z",
        "title": "Scheduled contractor van in East Yard",
        "detail": "A pre-registered maintenance van staged in East Yard for a known work order.",
        "severity": "low",
        "confidence": 0.93,
        "actor": "Vehicle C-04",
        "metadata": {"work_order_match": "WO-1182"},
    },
]
